### PR TITLE
Telecom constraint

### PR DESCRIPTION
**Pull request by ted-howard**
- Switched to constraint rule
- Check all container features not just first
- Return globalids of any container features not within distance

#13

### CODE REVIEW

**Comment by ted-howard** [comment]
@jalsup we plan to get this working nicely as a constraint rule and then port to validation eventually since it will only work in enterpise db.

**Comment by jalsup** [comment]
@ted-howard would it be safe to assume that the user experience would be that the case of user adding a feature to containment would fail of that feature were outside the tolerance?
Also, would the behaviour be the same for placing a Preset Template?
If so, then I think that is probably a better way.

**Comment by ted-howard** [comment]
@jalsup If I understand validation rules correctly, error features would be created if rule was violated but the feature would be allowed to be created. Constraint would prevent feature from being created (or moved outside tolerance if it already exists). Assuming the preset template properly triggers the constraint rule then the same behavior would be expected. You suggesting you like constraint more than validation?

**Comment by ted-howard** [comment]
however constraint would only test features getting added or edited. We wouldn't be able to test a dataset with existing features. I suppose we could offer both

**Comment by jalsup** [comment]
@ted-howard we should offer both.  There will be workflows where someone disables all attribute rules to bulk load data and then re-enables the attribute rules.  Having a batch validation option for any type of data check would be a good option to offer.

**Pull request merged**
